AUTHOR := Klassen Software Solutions
AUTHOR_URL := https://www.kss.cc/

include BuildSystem/swift/common.mk

build: Sources/crest/version.swift

check: Tests/LinuxMain.swift

TEST_SOURCES := $(wildcard Tests/KSS*Tests/*.swift)

Tests/LinuxMain.swift: $(TEST_SOURCES)
	swift test --generate-linuxmain

Sources/crest/version.swift: REVISION
	echo "// Auto-generated by Makefile. !!! DO NOT EDIT !!!" > $@
	echo "let VERSION=\"$(VERSION)\"" >> $@

clean: localclean

.PHONY: localclean
localclean:
	-rm -f Sources/crest/version.swift
