#if !canImport(ObjectiveC)
import XCTest

extension InputStreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputStreamReaderTests = [
        ("testSmallInputStream", testSmallInputStream),
    ]
}

extension crestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__crestTests = [
        ("testTheApplicationRuns", testTheApplicationRuns),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InputStreamReaderTests.__allTests__InputStreamReaderTests),
        testCase(crestTests.__allTests__crestTests),
    ]
}
#endif
